function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
	defos.set_cursor_visible(false)
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		print("Touch!")
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("open") then
		--open the door
	end
end